<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'id_item'       => '1',
                'name_product'  => 'Diamonds Mobile Legends',
                'code_product'  => 'DML11D',
                'price'         => '3000',
                'item'          => 'Diamonds 10 + 1',
            ],
            [
                'id_item'       => '1',
                'name_product'  => 'Diamonds Mobile Legends',
                'code_product'  => 'DML22D',
                'price'         => '6000',
                'item'          => 'Diamonds 20 + 2',
            ],
            [
                'id_item'       => '1',
                'name_product'  => 'Diamonds Mobile Legends',
                'code_product'  => 'DML56D',
                'price'         => '14000',
                'item'          => 'Diamonds 51 + 5',
            ],
            [
                'id_item'       => '1',
                'name_product'  => 'Diamonds Mobile Legends',
                'code_product'  => 'DML102D',
                'price'         => '27500',
                'item'          => 'Diamonds 102 + 10',
            ],
            [
                'id_item'       => '1',
                'name_product'  => 'Diamonds Mobile Legends',
                'code_product'  => 'DML203D',
                'price'         => '55000',
                'item'          => 'Diamonds 203 + 20',
            ],
            [
                'id_item'       => '1',
                'name_product'  => 'Diamonds Mobile Legends',
                'code_product'  => 'DML303D',
                'price'         => '85000',
                'item'          => 'Diamonds 303 + 33',
            ],
            [
                'id_item'       => '1',
                'name_product'  => 'Diamonds Mobile Legends',
                'code_product'  => 'DML504D',
                'price'         => '135000',
                'item'          => 'Diamonds 504 + 66',
            ],
            [
                'id_item'       => '1',
                'name_product'  => 'Diamonds Mobile Legends',
                'code_product'  => 'DML1007D',
                'price'         => '270000',
                'item'          => 'Diamonds 1007 + 156',
            ],
            [
                'id_item'       => '1',
                'name_product'  => 'Diamonds Mobile Legends',
                'code_product'  => 'DML2015D',
                'price'         => '550000',
                'item'          => 'Diamonds 2015 + 383',
            ],
            [
                'id_item'       => '1',
                'name_product'  => 'Diamonds Mobile Legends',
                'code_product'  => 'DML5035D',
                'price'         => '1300000',
                'item'          => 'Diamonds 5035 + 1007',
            ],
            [
                'id_item'       => '2',
                'name_product'  => 'PUBG Mobile UC Coin',
                'code_product'  => 'PUGM15UC',
                'price'         => '3000',
                'item'          => '15 UC',
            ],
            [
                'id_item'       => '2',
                'name_product'  => 'PUBG Mobile UC Coin',
                'code_product'  => 'PUGM30UC',
                'price'         => '6000',
                'item'          => '30 UC',
            ],
            [
                'id_item'       => '2',
                'name_product'  => 'PUBG Mobile UC Coin',
                'code_product'  => 'PUGM60UC',
                'price'         => '12850',
                'item'          => '60 UC',
            ],
            [
                'id_item'       => '2',
                'name_product'  => 'PUBG Mobile UC Coin',
                'code_product'  => 'PUGM210UC',
                'price'         => '44380',
                'item'          => '210 UC',
            ],
            [
                'id_item'       => '2',
                'name_product'  => 'PUBG Mobile UC Coin',
                'code_product'  => 'PUGM325UC',
                'price'         => '64028',
                'item'          => '300 + 25 UC',
            ],
            [
                'id_item'       => '2',
                'name_product'  => 'PUBG Mobile UC Coin',
                'code_product'  => 'PUGM480UC',
                'price'         => '102500',
                'item'          => '480 + 25 UC',
            ],
            [
                'id_item'       => '2',
                'name_product'  => 'PUBG Mobile UC Coin',
                'code_product'  => 'PUGM660UC',
                'price'         => '140000',
                'item'          => '660 + 60 UC',
            ],
            [
                'id_item'       => '2',
                'name_product'  => 'PUBG Mobile UC Coin',
                'code_product'  => 'PUGM900UC',
                'price'         => '192300',
                'item'          => '900 + 85 UC',
            ],
            [
                'id_item'       => '2',
                'name_product'  => 'PUBG Mobile UC Coin',
                'code_product'  => 'PUGM180UC',
                'price'         => '384125',
                'item'          => '1800 + 325 UC',
            ],
            [
                'id_item'       => '2',
                'name_product'  => 'PUBG Mobile UC Coin',
                'code_product'  => 'PUGM3850UC',
                'price'         => '640120',
                'item'          => '3000 + 850 UC',
            ],
            [
                'id_item'       => '3',
                'name_product'  => 'Genshin Impact Genesis Crystal',
                'code_product'  => 'GI60CRYST',
                'price'         => '10000',
                'item'          => '60 Genesis Crystal',
            ],
            [
                'id_item'       => '3',
                'name_product'  => 'Genshin Impact Genesis Crystal',
                'code_product'  => 'GI330CRYST',
                'price'         => '53000',
                'item'          => '300 + 30 Genesis Crystal',
            ],
            [
                'id_item'       => '3',
                'name_product'  => 'Genshin Impact Primogem Bundle',
                'code_product'  => 'GI980CRYST',
                'price'         => '275075',
                'item'          => '980 Genesis Crystal',
            ],
            [
                'id_item'       => '3',
                'name_product'  => 'Genshin Impact Primogem Bundle',
                'code_product'  => 'GI3280CRYST',
                'price'         => '880500',
                'item'          => '3280 Genesis Crystal',
            ],
            [
                'id_item'       => '3',
                'name_product'  => 'Genshin Impact Primogem Bundle',
                'code_product'  => 'GI6480CRYST',
                'price'         => '1085139',
                'item'          => '6480+1600 Genesis Crystals',
            ],
            [
                'id_item'       => '4',
                'name_product'  => 'Higgs Domino 1M Koin Emas-MD',
                'code_product'  => 'HDD1MMD',
                'price'         => '150',
                'item'          => '1M koin emas',
            ],
            [
                'id_item'       => '4',
                'name_product'  => 'Higgs Domino 5M Koin Emas-MD',
                'code_product'  => 'HDD5MMD',
                'price'         => '1000',
                'item'          => '5M koin emas',
            ],
            [
                'id_item'       => '4',
                'name_product'  => 'Higgs Domino 8M Koin Emas-MD',
                'code_product'  => 'HDD8MMD',
                'price'         => '1500',
                'item'          => '8M koin emas',
            ],
            [
                'id_item'       => '4',
                'name_product'  => 'Higgs Domino 100M Koin Emas-MD',
                'code_product'  => 'HDD100MMD',
                'price'         => '8000',
                'item'          => '100M koin emas',
            ],
            [
                'id_item'       => '4',
                'name_product'  => 'Higgs Domino 400M Koin Emas-MD',
                'code_product'  => 'HDD400MMD',
                'price'         => '26000',
                'item'          => '400M koin emas',
            ],
            [
                'id_item'       => '4',
                'name_product'  => 'Higgs Domino 1B Koin Emas-MD',
                'code_product'  => 'HDD1B',
                'price'         => '52000',
                'item'          => '1B koin emas',
            ],
            [
                'id_item'       => '4',
                'name_product'  => 'Higgs Domino 3B Koin Emas-MD',
                'code_product'  => 'HDD3B',
                'price'         => '152000',
                'item'          => '3B koin emas',
            ],
            [
                'id_item'       => '4',
                'name_product'  => 'Higgs Domino 10B Koin Emas-MD',
                'code_product'  => 'HDD10B',
                'price'         => '600000',
                'item'          => '10B koin emas',
            ],
            [
                'id_item'       => '5',
                'name_product'  => 'Honkai Impact 3 65 Crystals',
                'code_product'  => 'HI65C',
                'price'         => '13000',
                'item'          => '65 Crystals',
            ],
            [
                'id_item'       => '5',
                'name_product'  => 'Honkai Impact 3 330 Crystals',
                'code_product'  => 'HI330C',
                'price'         => '58000',
                'item'          => '330 Crystals',
            ],
            [
                'id_item'       => '5',
                'name_product'  => 'Honkai Impact 3 710 Crystals',
                'code_product'  => 'HI710C',
                'price'         => '116000',
                'item'          => '710 Crystals',
            ],
            [
                'id_item'       => '5',
                'name_product'  => 'Honkai Impact 3 1430 Crystals',
                'code_product'  => 'HI1430C',
                'price'         => '174000',
                'item'          => '1430 Crystals',
            ],
            [
                'id_item'       => '5',
                'name_product'  => 'Honkai Impact 3 3860 Crystals',
                'code_product'  => 'HI3860C',
                'price'         => '580000',
                'item'          => '3860 Crystals',
            ],
            [
                'id_item'       => '5',
                'name_product'  => 'Honkai Impact 3 8088 Crystals',
                'code_product'  => 'HI8088C',
                'price'         => '1160000',
                'item'          => '8088 Crystals',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 80 Gems',
                'code_product'  => 'COC80G',
                'price'         => '12000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 500 Gems',
                'code_product'  => 'COC500G',
                'price'         => '60000',
                'item'          => '500 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 2500 Gems',
                'code_product'  => 'COC80G',
                'price'         => '225000',
                'item'          => '2500 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 6500 Gems',
                'code_product'  => 'COC6500G',
                'price'         => '500000',
                'item'          => '6500 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 14000 Gems',
                'code_product'  => 'COC14000G',
                'price'         => '1000000',
                'item'          => '14000 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 80 Gems',
                'code_product'  => 'COC80G',
                'price'         => '17000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 80 Gems',
                'code_product'  => 'COC80G',
                'price'         => '17000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 80 Gems',
                'code_product'  => 'COC80G',
                'price'         => '17000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 80 Gems',
                'code_product'  => 'COC80G',
                'price'         => '17000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 80 Gems',
                'code_product'  => 'COC80G',
                'price'         => '17000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 80 Gems',
                'code_product'  => 'COC80G',
                'price'         => '17000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 80 Gems',
                'code_product'  => 'COC80G',
                'price'         => '17000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 80 Gems',
                'code_product'  => 'COC80G',
                'price'         => '17000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '7',
                'name_product'  => 'Clash Royale 80 Gems',
                'code_product'  => 'CR80G',
                'price'         => '13000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '7',
                'name_product'  => 'Clash Royale 500 Gems',
                'code_product'  => 'CR500G',
                'price'         => '60000',
                'item'          => '500 Gems',
            ],
            [
                'id_item'       => '7',
                'name_product'  => 'Clash Royale Gold Pass',
                'code_product'  => 'CRGP00',
                'price'         => '69000',
                'item'          => 'Gold Pass',
            ],
            [
                'id_item'       => '7',
                'name_product'  => 'Clash Royale 1200 Gems',
                'code_product'  => 'CR1200G',
                'price'         => '115000',
                'item'          => '1200 Gems',
            ],
            [
                'id_item'       => '7',
                'name_product'  => 'Clash Royale Diamond Pass',
                'code_product'  => 'CRDPASS0',
                'price'         => '135000',
                'item'          => 'Diamond Pass',
            ],
            [
                'id_item'       => '7',
                'name_product'  => 'Clash Royale 2500 Gems',
                'code_product'  => 'CR2500G',
                'price'         => '235000',
                'item'          => '2500 Gems',
            ],
            [
                'id_item'       => '7',
                'name_product'  => 'Clash Royale 6500 Gems',
                'code_product'  => 'CR6500G',
                'price'         => '585000',
                'item'          => '6500 Gems',
            ],
            [
                'id_item'       => '7',
                'name_product'  => 'Clash Royale 14000 Gems',
                'code_product'  => 'CR14000G',
                'price'         => '1100000',
                'item'          => '14000 Gems',
            ],
            [
                'id_item'       => '8',
                'name_product'  => 'Brawl Stars 30 Gems',
                'code_product'  => 'BRS30G',
                'price'         => '28000',
                'item'          => '30 Gems',
            ],
            [
                'id_item'       => '8',
                'name_product'  => 'Brawl Stars 80 Gems',
                'code_product'  => 'BRS80G',
                'price'         => '65000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '8',
                'name_product'  => 'Brawl Stars 170  Gems',
                'code_product'  => 'BRS170G',
                'price'         => '13000',
                'item'          => '170  Gems',
            ],
            [
                'id_item'       => '8',
                'name_product'  => 'Brawl Stars Brawl Pass',
                'code_product'  => 'BRSPASS00',
                'price'         => '130000',
                'item'          => 'Brawl Pass',
            ],
            [
                'id_item'       => '8',
                'name_product'  => 'Brawl Stars 360 Gems',
                'code_product'  => 'BRS360G',
                'price'         => '255000',
                'item'          => '360 Gems',
            ],
            [
                'id_item'       => '8',
                'name_product'  => 'Brawl Stars 950 Gems',
                'code_product'  => 'BRS950G',
                'price'         => '640000',
                'item'          => '950 Gems',
            ],
            [
                'id_item'       => '8',
                'name_product'  => 'Brawl Stars 2000 Gems',
                'code_product'  => 'BRS2000G',
                'price'         => '65000',
                'item'          => '2000 Gems',
            ],
            [
                'id_item'       => '9',
                'name_product'  => 'Free Fire 20 Diamond',
                'code_product'  => 'FF20D',
                'price'         => '4000',
                'item'          => '20 Diamond',
            ],
            [
                'id_item'       => '9',
                'name_product'  => 'Free Fire 30 Diamond',
                'code_product'  => 'FF30D',
                'price'         => '6000',
                'item'          => '30 Diamond',
            ],
            [
                'id_item'       => '9',
                'name_product'  => 'Free Fire 40 Diamond',
                'code_product'  => 'FF40D',
                'price'         => '6100',
                'item'          => '40 Diamond',
            ],
            [
                'id_item'       => '9',
                'name_product'  => 'Free Fire 70 Diamond',
                'code_product'  => 'FF70D',
                'price'         => '10000',
                'item'          => '70 Diamond',
            ],
            [
                'id_item'       => '9',
                'name_product'  => 'Free Fire 100 Diamond',
                'code_product'  => 'FF100D',
                'price'         => '14000',
                'item'          => '100 Diamond',
            ],
            [
                'id_item'       => '9',
                'name_product'  => 'Free Fire 150 Diamond',
                'code_product'  => 'FF150D',
                'price'         => '21000',
                'item'          => '150 Diamond',
            ],
            [
                'id_item'       => '9',
                'name_product'  => 'Free Fire 200 Diamond',
                'code_product'  => 'FF200D',
                'price'         => '28000',
                'item'          => '200 Diamond',
            ],
            [
                'id_item'       => '9',
                'name_product'  => 'Free Fire 930 Diamond',
                'code_product'  => 'FF930D',
                'price'         => '140000',
                'item'          => '930 Diamond',
            ],
            [
                'id_item'       => '9',
                'name_product'  => 'Free Fire 1000 Diamond',
                'code_product'  => 'FF1000D',
                'price'         => '150000',
                'item'          => '1000 Diamond',
            ],
            [
                'id_item'       => '9',
                'name_product'  => 'Free Fire 2000 Diamond',
                'code_product'  => 'FF2000D',
                'price'         => '260000',
                'item'          => '2000 Diamond',
            ],
            [
                'id_item'       => '10',
                'name_product'  => '1200 Point Blank Cash',
                'code_product'  => 'PB12IC',
                'price'         => '10000',
                'item'          => '1200 PB Cash',
            ],
            [
                'id_item'       => '10',
                'name_product'  => '2400 Point Blank Cash',
                'code_product'  => 'PB24IC',
                'price'         => '20000',
                'item'          => '2400 PB Cash',
            ],
            [
                'id_item'       => '10',
                'name_product'  => '6000 Point Blank Cash',
                'code_product'  => 'PB60IC',
                'price'         => '50000',
                'item'          => '6000 PB Cash',
            ],
            [
                'id_item'       => '10',
                'name_product'  => '12000 Point Blank Cash',
                'code_product'  => 'PB120IC',
                'price'         => '95000',
                'item'          => '12000 PB Cash',
            ],
            [
                'id_item'       => '10',
                'name_product'  => '24000 Point Blank Cash',
                'code_product'  => 'PB24IC',
                'price'         => '175000',
                'item'          => '24000 PB Cash',
            ],
            [
                'id_item'       => '10',
                'name_product'  => '36000 Point Blank Cash',
                'code_product'  => 'PB36IC',
                'price'         => '270000',
                'item'          => '36000 PB Cash',
            ],
            [
                'id_item'       => '10',
                'name_product'  => '60000 Point Blank Cash',
                'code_product'  => 'PB60IC',
                'price'         => '438000',
                'item'          => '60000 PB Cash',
            ],
            [
                'id_item'       => '11',
                'name_product'  => 'Valorant 125 Points',
                'code_product'  => 'VL125P',
                'price'         => '15000',
                'item'          => '125 Point',
            ],
            [
                'id_item'       => '11',
                'name_product'  => 'Valorant 300 Points',
                'code_product'  => 'VL300P',
                'price'         => '45000',
                'item'          => '300 Point',
            ],
            [
                'id_item'       => '11',
                'name_product'  => 'Valorant 700 Points',
                'code_product'  => 'VL700P',
                'price'         => '75000',
                'item'          => '700 Point',
            ],
            [
                'id_item'       => '11',
                'name_product'  => 'Valorant 1120 Points',
                'code_product'  => 'VL1120P',
                'price'         => '120000',
                'item'          => '1120 Point',
            ],
            [
                'id_item'       => '11',
                'name_product'  => 'Valorant 1650 Points',
                'code_product'  => 'VL1650P',
                'price'         => '185000',
                'item'          => '1650 Point',
            ],
            [
                'id_item'       => '11',
                'name_product'  => 'Valorant 2075 Points',
                'code_product'  => 'VL2075P',
                'price'         => '215000',
                'item'          => '2075 Point',
            ],
            [
                'id_item'       => '11',
                'name_product'  => 'Valorant 2400 Points',
                'code_product'  => 'VL2400P',
                'price'         => '230000',
                'item'          => '2400 Point',
            ],
            [
                'id_item'       => '11',
                'name_product'  => 'Valorant 3100 Points',
                'code_product'  => 'VL3100P',
                'price'         => '310000',
                'item'          => '3100 Point',
            ],
            [
                'id_item'       => '11',
                'name_product'  => 'Valorant 4000 Points',
                'code_product'  => 'VL4000P',
                'price'         => '365000',
                'item'          => '4000 Point',
            ],
            [
                'id_item'       => '11',
                'name_product'  => 'Valorant 7000 Points',
                'code_product'  => 'VL7000P',
                'price'         => '680000',
                'item'          => '7000 Point',
            ],
            [
                'id_item'       => '11',
                'name_product'  => 'Valorant 8650 Points',
                'code_product'  => 'VL8650P',
                'price'         => '815000',
                'item'          => '8650 Point',
            ],
            [
                'id_item'       => '11',
                'name_product'  => 'Valorant 10550 Points',
                'code_product'  => 'VL10550P',
                'price'         => '965000',
                'item'          => '10550 Point',
            ],
            [
                'id_item'       => '11',
                'name_product'  => 'Valorant 16300 Points',
                'code_product'  => 'VL16300P',
                'price'         => '1460000',
                'item'          => '16300 Point',
            ],
            [
                'id_item'       => '12',
                'name_product'  => 'League of Legends Wild Rift 105 Wild Cores',
                'code_product'  => 'LOL105WCR',
                'price'         => '14500',
                'item'          => '105 Wild Cores',
            ],
            [
                'id_item'       => '12',
                'name_product'  => 'League of Legends Wild Rift 300 Wild Cores',
                'code_product'  => 'LOL300WCR',
                'price'         => '50000',
                'item'          => '300 Wild Cores',
            ],
            [
                'id_item'       => '12',
                'name_product'  => 'League of Legends Wild Rift 420 Wild Cores',
                'code_product'  => 'LOL420WCR',
                'price'         => '55000',
                'item'          => '420 Wild Cores',
            ],
            [
                'id_item'       => '12',
                'name_product'  => 'League of Legends Wild Rift 625 Wild Cores',
                'code_product'  => 'LOL625WCR',
                'price'         => '88000',
                'item'          => '625 Wild Cores',
            ],
            [
                'id_item'       => '12',
                'name_product'  => 'League of Legends Wild Rift 605 Wild Cores',
                'code_product'  => 'LOL605WCR',
                'price'         => '75000',
                'item'          => '605 Wild Cores',
            ],
            [
                'id_item'       => '12',
                'name_product'  => 'League of Legends Wild Rift 700 Wild Cores',
                'code_product'  => 'LOL700WCR',
                'price'         => '100000',
                'item'          => '700 Wild Cores',
            ],
            [
                'id_item'       => '12',
                'name_product'  => 'League of Legends Wild Rift 1135 Wild Cores',
                'code_product'  => 'LOL1135WCR',
                'price'         => '140000',
                'item'          => '1135 Wild Cores',
            ],
            [
                'id_item'       => '12',
                'name_product'  => 'League of Legends Wild Rift 1375 Wild Cores',
                'code_product'  => 'LOL1375WCR',
                'price'         => '184000',
                'item'          => '1375 Wild Cores',
            ],
            [
                'id_item'       => '12',
                'name_product'  => 'League of Legends Wild Rift 3010 Wild Cores',
                'code_product'  => 'LOL3010WCR',
                'price'         => '335000',
                'item'          => '3010 Wild Cores',
            ],
            [
                'id_item'       => '12',
                'name_product'  => 'League of Legends Wild Rift 6210 Wild Cores',
                'code_product'  => 'LOL6210WCR',
                'price'         => '690000',
                'item'          => '6210 Wild Cores',
            ],
            [
                'id_item'       => '12',
                'name_product'  => 'League of Legends Wild Rift 7005 Wild Cores',
                'code_product'  => 'LOL7005WCR',
                'price'         => '695000',
                'item'          => '7005 Wild Cores',
            ],
            [
                'id_item'       => '12',
                'name_product'  => 'League of Legends Wild Rift 8150 Wild Cores',
                'code_product'  => 'LOL8150WCR',
                'price'         => '1000000',
                'item'          => '8150 Wild Cores',
            ],
            [
                'id_item'       => '13',
                'name_product'  => 'Ragnarok Mobile Eternal Love 30 Big Cat Coin',
                'code_product'  => 'RME30BCC',
                'price'         => '90000',
                'item'          => '30 Big Cat Coin',
            ],
            [
                'id_item'       => '13',
                'name_product'  => 'Ragnarok Mobile Eternal Love 120000 Zeny',
                'code_product'  => 'RME120Z',
                'price'         => '35000',
                'item'          => '120000 Zeny',
            ],
            [
                'id_item'       => '14',
                'name_product'  => 'Dragon Raja 66 Coupons',
                'code_product'  => 'DRA66C',
                'price'         => '13500',
                'item'          => '66 Coupons',
            ],
            [
                'id_item'       => '14',
                'name_product'  => 'Dragon Raja 76 Coupons',
                'code_product'  => 'DRA76C',
                'price'         => '15500',
                'item'          => '76 Coupons',
            ],
            [
                'id_item'       => '14',
                'name_product'  => 'Dragon Raja 90 Coupons',
                'code_product'  => 'DRA90C',
                'price'         => '19200',
                'item'          => '90 Coupons',
            ],
            [
                'id_item'       => '14',
                'name_product'  => 'Dragon Raja 264 Coupons',
                'code_product'  => 'DRA264C',
                'price'         => '50000',
                'item'          => '264 Coupons',
            ],
            [
                'id_item'       => '14',
                'name_product'  => 'Dragon Raja 456 Coupons',
                'code_product'  => 'DRA456C',
                'price'         => '85000',
                'item'          => '456 Coupons',
            ],
            [
                'id_item'       => '14',
                'name_product'  => 'Dragon Raja 820 Coupons',
                'code_product'  => 'DRA820C',
                'price'         => '14500',
                'item'          => '820 Coupons',
            ],
            [
                'id_item'       => '14',
                'name_product'  => 'Dragon Raja 988 Coupons',
                'code_product'  => 'DRA988C',
                'price'         => '18500',
                'item'          => '988 Coupons',
            ],
            [
                'id_item'       => '14',
                'name_product'  => 'Dragon Raja 1098 Coupons',
                'code_product'  => 'DRA1098C',
                'price'         => '187100',
                'item'          => '1098 Coupons',
            ],
            [
                'id_item'       => '14',
                'name_product'  => 'Dragon Raja 2246 Coupons',
                'code_product'  => 'DRA2246C',
                'price'         => '368200',
                'item'          => '2246 Coupons',
            ],
            [
                'id_item'       => '14',
                'name_product'  => 'Dragon Raja 2553 Coupons',
                'code_product'  => 'DRA2553C',
                'price'         => '432500',
                'item'          => '2553 Coupons',
            ],
            [
                'id_item'       => '14',
                'name_product'  => 'Dragon Raja 3768 Coupons',
                'code_product'  => 'DRA3768C',
                'price'         => '610230',
                'item'          => '3768 Coupons',
            ],
            [
                'id_item'       => '14',
                'name_product'  => 'Dragon Raja 5161 Coupons',
                'code_product'  => 'DRA5161C',
                'price'         => '850100',
                'item'          => '5161 Coupons',
            ],
            [
                'id_item'       => '14',
                'name_product'  => 'Dragon Raja 7546 Coupons',
                'code_product'  => 'DRA7546C',
                'price'         => '1218000',
                'item'          => '7546 Coupons',
            ],
            [
                'id_item'       => '14',
                'name_product'  => 'Dragon Raja 9056 Coupons',
                'code_product'  => 'DRA9056C',
                'price'         => '1409150',
                'item'          => '9056 Coupons',
            ],
            [
                'id_item'       => '14',
                'name_product'  => 'Dragon Raja 15092 Coupons',
                'code_product'  => 'DRA15092C',
                'price'         => '2429000',
                'item'          => '15092 Coupons',
            ],
            [
                'id_item'       => '15',
                'name_product'  => '8 Ball Pool 20000 Coin',
                'code_product'  => 'PBALL20K',
                'price'         => '15200',
                'item'          => '20000 Coin',
            ],
            [
                'id_item'       => '15',
                'name_product'  => '8 Ball Pool 52000 Coin',
                'code_product'  => 'PBALL52K',
                'price'         => '35100',
                'item'          => '52000 Coin',
            ],
            [
                'id_item'       => '15',
                'name_product'  => '8 Ball Pool 112000 Coin',
                'code_product'  => 'PBALL112K',
                'price'         => '65800',
                'item'          => '112000 Coin',
            ],
            [
                'id_item'       => '15',
                'name_product'  => '8 Ball Pool 256000 Coin',
                'code_product'  => 'PBALL256K',
                'price'         => '132800',
                'item'          => '256000 Coin',
            ],
            [
                'id_item'       => '15',
                'name_product'  => '8 Ball Pool 800000 Coin',
                'code_product'  => 'PBALL800K',
                'price'         => '320400',
                'item'          => '800000 Coin',
            ],
            [
                'id_item'       => '15',
                'name_product'  => '8 Ball Pool 2000000 Coin',
                'code_product'  => 'PBALL2000K',
                'price'         => '650250',
                'item'          => '2000000 Coin',
            ],
            [
                'id_item'       => '21',
                'name_product'  => 'Joki Magic Chess',
                'code_product'  => 'GIM40',
                'price'         => '7000',
                'item'          => 'Grandmaster / 40 Point',
            ],
            [
                'id_item'       => '21',
                'name_product'  => 'Joki Magic Chess',
                'code_product'  => 'EPIC40',
                'price'         => '7000',
                'item'          => 'Epic / 40 Point',
            ],
            [
                'id_item'       => '21',
                'name_product'  => 'Joki Magic Chess',
                'code_product'  => 'LEG40',
                'price'         => '9000',
                'item'          => 'Legend / 40 Point',
            ],
            [
                'id_item'       => '21',
                'name_product'  => 'Joki Magic Chess',
                'code_product'  => 'MYT40',
                'price'         => '9000',
                'item'          => 'Mythic / 40 Point',
            ],
            [
                'id_item'       => '21',
                'name_product'  => 'Joki Magic Chess',
                'code_product'  => 'MYTH40',
                'price'         => '20000',
                'item'          => 'Mythic Honor / 40 Point',
            ],
            [
                'id_item'       => '21',
                'name_product'  => 'Legend - Mythic',
                'code_product'  => 'LEGMYT',
                'price'         => '125000',
                'item'          => 'Legend - Mythic',
            ],
            [
                'id_item'       => '21',
                'name_product'  => 'Epic - Mythic',
                'code_product'  => 'EPMYT',
                'price'         => '150000',
                'item'          => 'Epic - Mythic',
            ],
            [
                'id_item'       => '21',
                'name_product'  => 'Grandmaster - Mythic',
                'code_product'  => 'GRAMYT',
                'price'         => '175000',
                'item'          => 'Grandmaster - Mythic',
            ],
            [
                'id_item'       => '21',
                'name_product'  => 'Master - Mythic',
                'code_product'  => 'MASTMYT',
                'price'         => '175000',
                'item'          => 'Master - Mythic',
            ],
            [
                'id_item'       => '21',
                'name_product'  => 'Elit - Mythic',
                'code_product'  => 'ELMYT',
                'price'         => '250000',
                'item'          => 'Elit - Mythic',
            ],
            [
                'id_item'       => '21',
                'name_product'  => 'Mythic - Mythic Honor',
                'code_product'  => 'MYTHON',
                'price'         => '300000',
                'item'          => 'Mythic - Mythic Honor',
            ],
            [
                'id_item'       => '21',
                'name_product'  => 'Warior - Mythic',
                'code_product'  => 'MYTHON',
                'price'         => '300000',
                'item'          => 'Warior - Mythic',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Joki Rank / Star',
                'code_product'  => 'JRS1',
                'price'         => '4000',
                'item'          => 'Master / Star',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Joki Rank / Star',
                'code_product'  => 'JRS2',
                'price'         => '5000',
                'item'          => 'GM / Star',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Joki Rank / Star',
                'code_product'  => 'JRS2',
                'price'         => '7500',
                'item'          => 'Epic / Star',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Joki Rank / Star',
                'code_product'  => 'JRS3',
                'price'         => '8500',
                'item'          => 'Legend / Star',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Joki Rank / Star',
                'code_product'  => 'JRS4',
                'price'         => '23000',
                'item'          => 'Mythic / Star',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Joki Rank / Star',
                'code_product'  => 'JRS5',
                'price'         => '26000',
                'item'          => 'Mythic / Honor Star',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Joki Rank / Star',
                'code_product'  => 'JRS6',
                'price'         => '29000',
                'item'          => 'Mythic Glory / Star',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Joki Rank / Star',
                'code_product'  => 'JRS7',
                'price'         => '30000',
                'item'          => 'Mythic Imortal / Star',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Grand Master',
                'code_product'  => 'RPGM1',
                'price'         => '125000',
                'item'          => 'GM V - Epic V',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Grand Master',
                'code_product'  => 'RPGM2',
                'price'         => '312000',
                'item'          => 'GM V - Legend V',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Grand Master',
                'code_product'  => 'RPGM3',
                'price'         => '425000',
                'item'          => 'GM I - Mythic',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Grand Master',
                'code_product'  => 'RPGM4',
                'price'         => '450000',
                'item'          => 'GM II - Mythic',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Grand Master',
                'code_product'  => 'RPGM5',
                'price'         => '475000',
                'item'          => 'GM III - Mythic',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Grand Master',
                'code_product'  => 'RPGM6',
                'price'         => '500000',
                'item'          => 'GM IV - Mythic',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Grand Master',
                'code_product'  => 'RPGM7',
                'price'         => '525000',
                'item'          => 'GM V - Mythic',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Epic',
                'code_product'  => 'RPEC1',
                'price'         => '187000',
                'item'          => 'Epic V - Legend V',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Epic',
                'code_product'  => 'RPEC2',
                'price'         => '250000',
                'item'          => 'Epic I - Mythic',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Epic',
                'code_product'  => 'RPEC3',
                'price'         => '289000',
                'item'          => 'Epic II - Mythic',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Epic',
                'code_product'  => 'RPEC4',
                'price'         => '325000',
                'item'          => 'Epic III - Mythic',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Epic',
                'code_product'  => 'RPEC5',
                'price'         => '362000',
                'item'          => 'Epic IV - Mythic',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Epic',
                'code_product'  => 'RPEC6',
                'price'         => '400000',
                'item'          => 'Epic V - Mythic',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Legend',
                'code_product'  => 'RPLEG1',
                'price'         => '212500',
                'item'          => 'Legend V - Mythic',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Legend',
                'code_product'  => 'RPLEG2',
                'price'         => '685000',
                'item'          => 'Legend V - Mythic Honor',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Legend',
                'code_product'  => 'RPLEG3',
                'price'         => '1340000',
                'item'          => 'Legend V - Mythic Glory',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Legend',
                'code_product'  => 'RPLEG4',
                'price'         => '2810000',
                'item'          => 'Legend V - Mythic Immortal',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Mythic',
                'code_product'  => 'RMYTC1G',
                'price'         => '234500',
                'item'          => 'Open Grading (Auto Star 15)',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Mythic',
                'code_product'  => 'RMYGH2',
                'price'         => '468500',
                'item'          => 'Mythic Grading - Mythic Honor (25)',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Mythic',
                'code_product'  => 'RMYMY2MG',
                'price'         => '1128000',
                'item'          => 'Mythic Grading - Mythic Glory (50)',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Mythic',
                'code_product'  => 'RMYMG2MI100',
                'price'         => '2598000',
                'item'          => 'Mythic Grading - Mythic Immortal (100)',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Mythic Honor',
                'code_product'  => 'RMH2MG2550',
                'price'         => '660000',
                'item'          => 'Mythic Honor (25) - Mythic Glory (50)',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Mythic Honor',
                'code_product'  => 'RMH2MG25100',
                'price'         => '2130000',
                'item'          => 'Mythic Honor (25) - Mythic Immortal (100)',
            ],
            [
                'id_item'       => '22',
                'name_product'  => 'Paket Mythic Glory',
                'code_product'  => 'RPMG50100',
                'price'         => '1470000',
                'item'          => 'Mythic Glory (50) - Mythic Immortal (100)',
            ],
            [
                'id_item'       => '23',
                'name_product'  => 'Jasa komen dari album',
                'code_product'  => 'JKOMPOS',
                'price'         => '10000',
                'item'          => 'Komen Postingan Instagram (No Private)',
            ],
            [
                'id_item'       => '23',
                'name_product'  => 'Jasa komen dari album',
                'code_product'  => 'JKMLBB',
                'price'         => '15000',
                'item'          => 'Komen Album Mobile Legends',
            ],
            [
                'id_item'       => '24',
                'name_product'  => 'Joki / Star',
                'code_product'  => 'JSTAR',
                'price'         => '5000',
                'item'          => 'GM / Star',
            ],
            [
                'id_item'       => '24',
                'name_product'  => 'Joki / Star',
                'code_product'  => 'ESTAR',
                'price'         => '7600',
                'item'          => 'Epic / Star',
            ],
            [
                'id_item'       => '24',
                'name_product'  => 'Joki / Star',
                'code_product'  => 'LSTAR',
                'price'         => '8600',
                'item'          => 'Legend / Star',
            ],
            [
                'id_item'       => '24',
                'name_product'  => 'Paket Grand Master',
                'code_product'  => 'PGM1',
                'price'         => '120000',
                'item'          => 'GM V - Epic V',
            ],
            [
                'id_item'       => '24',
                'name_product'  => 'Paket Grand Master',
                'code_product'  => 'PGM2',
                'price'         => '310000',
                'item'          => 'GM V - Legend V',
            ],
            [
                'id_item'       => '24',
                'name_product'  => 'Paket Grand Master',
                'code_product'  => 'PGM3',
                'price'         => '425000',
                'item'          => 'GM I - Mythic',
            ],
            [
                'id_item'       => '24',
                'name_product'  => 'Paket Grand Master',
                'code_product'  => 'PGM4',
                'price'         => '450000',
                'item'          => 'GM II - Mythic',
            ],
            [
                'id_item'       => '24',
                'name_product'  => 'Paket Grand Master',
                'code_product'  => 'PGM5',
                'price'         => '475000',
                'item'          => 'GM III - Mythic',
            ],
            [
                'id_item'       => '24',
                'name_product'  => 'Paket Grand Master',
                'code_product'  => 'PGM6',
                'price'         => '500000',
                'item'          => 'GM IV - Mythic',
            ],
            [
                'id_item'       => '24',
                'name_product'  => 'Paket Grand Master',
                'code_product'  => 'PGM7',
                'price'         => '525000',
                'item'          => 'GM V - Mythic V',
            ],
            [
                'id_item'       => '24',
                'name_product'  => 'Paket Epic',
                'code_product'  => 'PEPC1',
                'price'         => '185000',
                'item'          => 'Epic V - Legend V',
            ],
            [
                'id_item'       => '24',
                'name_product'  => 'Paket Epic',
                'code_product'  => 'PEPC2',
                'price'         => '250000',
                'item'          => 'Epic I - Mythic V',
            ],
            [
                'id_item'       => '24',
                'name_product'  => 'Paket Epic',
                'code_product'  => 'PEPC3',
                'price'         => '285000',
                'item'          => 'Epic II - Mythic V',
            ],
            [
                'id_item'       => '24',
                'name_product'  => 'Paket Epic',
                'code_product'  => 'PEPC4',
                'price'         => '325000',
                'item'          => 'Epic III - Mythic V',
            ],
            [
                'id_item'       => '24',
                'name_product'  => 'Paket Epic',
                'code_product'  => 'PEPC5',
                'price'         => '360000',
                'item'          => 'Epic IV - Mythic V',
            ],
            [
                'id_item'       => '24',
                'name_product'  => 'Paket Epic',
                'code_product'  => 'PEPC6',
                'price'         => '400000',
                'item'          => 'Epic V - Mythic V',
            ],
            [
                'id_item'       => '24',
                'name_product'  => 'Paket Legend',
                'code_product'  => 'PELB1',
                'price'         => '400000',
                'item'          => 'Legend V - Mythic',
            ],
            [
                'id_item'       => '24',
                'name_product'  => 'Paket Legend',
                'code_product'  => 'PELB2',
                'price'         => '710000',
                'item'          => 'Legend V - Mythic',
            ],
            [
                'id_item'       => '24',
                'name_product'  => 'Paket Mythic',
                'code_product'  => 'PMYTC1',
                'price'         => '251000',
                'item'          => 'Open Grading (Auto Star 15)',
            ],
            [
                'id_item'       => '24',
                'name_product'  => 'Paket Mythic',
                'code_product'  => 'PMYTC2',
                'price'         => '510000',
                'item'          => 'Mythic - Mythic Honor (25)',
            ],
            [
                'id_item'       => '26',
                'name_product'  => 'Gift Item',
                'code_product'  => 'GIFIT1',
                'price'         => '30000',
                'item'          => 'Create Squad',
            ],
            [
                'id_item'       => '26',
                'name_product'  => 'Gift Item',
                'code_product'  => 'GIFIT2',
                'price'         => '52000',
                'item'          => 'PO Starlight Card Aprill',
            ],
            [
                'id_item'       => '26',
                'name_product'  => 'Gift Item',
                'code_product'  => 'GIFIT3',
                'price'         => '600000',
                'item'          => 'Paket Starlight Card 1 Tahun',
            ],
            [
                'id_item'       => '26',
                'name_product'  => 'Gift Skin',
                'code_product'  => 'GIFSK1',
                'price'         => '98000',
                'item'          => 'Fredrin All Star Skin 28 Maret (629 Diamond)',
            ],
            [
                'id_item'       => '27',
                'name_product'  => 'Sewa Room Tournament',
                'code_product'  => 'PSOL1M',
                'price'         => '20000',
                'item'          => 'Paket Solo / 1 Match (1 Player)',
            ],
            [
                'id_item'       => '27',
                'name_product'  => 'Sewa Room Tournament',
                'code_product'  => 'PSOL2M',
                'price'         => '20000',
                'item'          => 'Paket By 1 / Couple / 1 Match (2 Player)',
            ],
            [
                'id_item'       => '27',
                'name_product'  => 'Sewa Room Tournament',
                'code_product'  => 'PSOL3M',
                'price'         => '30000',
                'item'          => 'Room Tournament / 1 Match (10 Player)',
            ],
            [
                'id_item'       => '27',
                'name_product'  => 'Sewa Room Tournament',
                'code_product'  => 'PSOL4M',
                'price'         => '50000',
                'item'          => 'Room Tournament / 1 Jam (10 Player)',
            ],
            [
                'id_item'       => '27',
                'name_product'  => 'Sewa Room Tournament',
                'code_product'  => 'PSOL5M',
                'price'         => '350000',
                'item'          => 'Room Tournament / VIP 12 Jam (10 Player)',
            ],
            [
                'id_item'       => '27',
                'name_product'  => 'Sewa Room Tournament',
                'code_product'  => 'PSOL6M',
                'price'         => '650000',
                'item'          => 'Room Tournament / VVIP 24 Jam (10 Player)',
            ],
            [
                'id_item'       => '28',
                'name_product'  => 'Joki Montage',
                'code_product'  => 'JOVMON1',
                'price'         => '60000',
                'item'          => 'Video Polos No Edit / 1 Menit',
            ],
        ];

        $this->db->table('products')->insertBatch($data);
    }
}
