<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'id_item'       => '1',
                'name_product'  => 'Diamonds Mobile Legends',
                'code_product'  => 'DML11D',
                'price'         => '3000',
                'item'          => 'Diamonds 10 + 1',
            ],
            [
                'id_item'       => '1',
                'name_product'  => 'Diamonds Mobile Legends',
                'code_product'  => 'DML22D',
                'price'         => '6000',
                'item'          => 'Diamonds 20 + 2',
            ],
            [
                'id_item'       => '1',
                'name_product'  => 'Diamonds Mobile Legends',
                'code_product'  => 'DML56D',
                'price'         => '14000',
                'item'          => 'Diamonds 51 + 5',
            ],
            [
                'id_item'       => '1',
                'name_product'  => 'Diamonds Mobile Legends',
                'code_product'  => 'DML102D',
                'price'         => '27500',
                'item'          => 'Diamonds 102 + 10',
            ],
            [
                'id_item'       => '1',
                'name_product'  => 'Diamonds Mobile Legends',
                'code_product'  => 'DML203D',
                'price'         => '55000',
                'item'          => 'Diamonds 203 + 20',
            ],
            [
                'id_item'       => '1',
                'name_product'  => 'Diamonds Mobile Legends',
                'code_product'  => 'DML303D',
                'price'         => '85000',
                'item'          => 'Diamonds 303 + 33',
            ],
            [
                'id_item'       => '1',
                'name_product'  => 'Diamonds Mobile Legends',
                'code_product'  => 'DML504D',
                'price'         => '135000',
                'item'          => 'Diamonds 504 + 66',
            ],
            [
                'id_item'       => '1',
                'name_product'  => 'Diamonds Mobile Legends',
                'code_product'  => 'DML1007D',
                'price'         => '270000',
                'item'          => 'Diamonds 1007 + 156',
            ],
            [
                'id_item'       => '1',
                'name_product'  => 'Diamonds Mobile Legends',
                'code_product'  => 'DML2015D',
                'price'         => '550000',
                'item'          => 'Diamonds 2015 + 383',
            ],
            [
                'id_item'       => '1',
                'name_product'  => 'Diamonds Mobile Legends',
                'code_product'  => 'DML5035D',
                'price'         => '1300000',
                'item'          => 'Diamonds 5035 + 1007',
            ],
            [
                'id_item'       => '2',
                'name_product'  => 'PUBG Mobile UC Coin',
                'code_product'  => 'PUGM15UC',
                'price'         => '3000',
                'item'          => '15 UC',
            ],
            [
                'id_item'       => '2',
                'name_product'  => 'PUBG Mobile UC Coin',
                'code_product'  => 'PUGM30UC',
                'price'         => '6000',
                'item'          => '30 UC',
            ],
            [
                'id_item'       => '2',
                'name_product'  => 'PUBG Mobile UC Coin',
                'code_product'  => 'PUGM60UC',
                'price'         => '12850',
                'item'          => '60 UC',
            ],
            [
                'id_item'       => '2',
                'name_product'  => 'PUBG Mobile UC Coin',
                'code_product'  => 'PUGM210UC',
                'price'         => '44380',
                'item'          => '210 UC',
            ],
            [
                'id_item'       => '2',
                'name_product'  => 'PUBG Mobile UC Coin',
                'code_product'  => 'PUGM325UC',
                'price'         => '64028',
                'item'          => '300 + 25 UC',
            ],
            [
                'id_item'       => '2',
                'name_product'  => 'PUBG Mobile UC Coin',
                'code_product'  => 'PUGM480UC',
                'price'         => '102500',
                'item'          => '480 + 25 UC',
            ],
            [
                'id_item'       => '2',
                'name_product'  => 'PUBG Mobile UC Coin',
                'code_product'  => 'PUGM660UC',
                'price'         => '140000',
                'item'          => '660 + 60 UC',
            ],
            [
                'id_item'       => '2',
                'name_product'  => 'PUBG Mobile UC Coin',
                'code_product'  => 'PUGM900UC',
                'price'         => '192300',
                'item'          => '900 + 85 UC',
            ],
            [
                'id_item'       => '2',
                'name_product'  => 'PUBG Mobile UC Coin',
                'code_product'  => 'PUGM180UC',
                'price'         => '384125',
                'item'          => '1800 + 325 UC',
            ],
            [
                'id_item'       => '2',
                'name_product'  => 'PUBG Mobile UC Coin',
                'code_product'  => 'PUGM3850UC',
                'price'         => '640120',
                'item'          => '3000 + 850 UC',
            ],
            [
                'id_item'       => '3',
                'name_product'  => 'Genshin Impact Genesis Crystal',
                'code_product'  => 'GI60CRYST',
                'price'         => '10000',
                'item'          => '60 Genesis Crystal',
            ],
            [
                'id_item'       => '3',
                'name_product'  => 'Genshin Impact Genesis Crystal',
                'code_product'  => 'GI330CRYST',
                'price'         => '53000',
                'item'          => '300 + 30 Genesis Crystal',
            ],
            [
                'id_item'       => '3',
                'name_product'  => 'Genshin Impact Primogem Bundle',
                'code_product'  => 'GI980CRYST',
                'price'         => '275075',
                'item'          => '980 Genesis Crystal',
            ],
            [
                'id_item'       => '3',
                'name_product'  => 'Genshin Impact Primogem Bundle',
                'code_product'  => 'GI3280CRYST',
                'price'         => '880500',
                'item'          => '3280 Genesis Crystal',
            ],
            [
                'id_item'       => '3',
                'name_product'  => 'Genshin Impact Primogem Bundle',
                'code_product'  => 'GI6480CRYST',
                'price'         => '1085139',
                'item'          => '6480+1600 Genesis Crystals',
            ],
            [
                'id_item'       => '4',
                'name_product'  => 'Higgs Domino 1M Koin Emas-MD',
                'code_product'  => 'HDD1MMD',
                'price'         => '150',
                'item'          => '1M koin emas',
            ],
            [
                'id_item'       => '4',
                'name_product'  => 'Higgs Domino 5M Koin Emas-MD',
                'code_product'  => 'HDD5MMD',
                'price'         => '1000',
                'item'          => '5M koin emas',
            ],
            [
                'id_item'       => '4',
                'name_product'  => 'Higgs Domino 8M Koin Emas-MD',
                'code_product'  => 'HDD8MMD',
                'price'         => '1500',
                'item'          => '8M koin emas',
            ],
            [
                'id_item'       => '4',
                'name_product'  => 'Higgs Domino 100M Koin Emas-MD',
                'code_product'  => 'HDD100MMD',
                'price'         => '8000',
                'item'          => '100M koin emas',
            ],
            [
                'id_item'       => '4',
                'name_product'  => 'Higgs Domino 400M Koin Emas-MD',
                'code_product'  => 'HDD400MMD',
                'price'         => '26000',
                'item'          => '400M koin emas',
            ],
            [
                'id_item'       => '4',
                'name_product'  => 'Higgs Domino 1B Koin Emas-MD',
                'code_product'  => 'HDD1B',
                'price'         => '52000',
                'item'          => '1B koin emas',
            ],
            [
                'id_item'       => '4',
                'name_product'  => 'Higgs Domino 3B Koin Emas-MD',
                'code_product'  => 'HDD3B',
                'price'         => '152000',
                'item'          => '3B koin emas',
            ],
            [
                'id_item'       => '4',
                'name_product'  => 'Higgs Domino 10B Koin Emas-MD',
                'code_product'  => 'HDD10B',
                'price'         => '600000',
                'item'          => '10B koin emas',
            ],
            [
                'id_item'       => '5',
                'name_product'  => 'Honkai Impact 3 65 Crystals',
                'code_product'  => 'HI65C',
                'price'         => '13000',
                'item'          => '65 Crystals',
            ],
            [
                'id_item'       => '5',
                'name_product'  => 'Honkai Impact 3 330 Crystals',
                'code_product'  => 'HI330C',
                'price'         => '58000',
                'item'          => '330 Crystals',
            ],
            [
                'id_item'       => '5',
                'name_product'  => 'Honkai Impact 3 710 Crystals',
                'code_product'  => 'HI710C',
                'price'         => '116000',
                'item'          => '710 Crystals',
            ],
            [
                'id_item'       => '5',
                'name_product'  => 'Honkai Impact 3 1430 Crystals',
                'code_product'  => 'HI1430C',
                'price'         => '174000',
                'item'          => '1430 Crystals',
            ],
            [
                'id_item'       => '5',
                'name_product'  => 'Honkai Impact 3 3860 Crystals',
                'code_product'  => 'HI3860C',
                'price'         => '580000',
                'item'          => '3860 Crystals',
            ],
            [
                'id_item'       => '5',
                'name_product'  => 'Honkai Impact 3 8088 Crystals',
                'code_product'  => 'HI8088C',
                'price'         => '1160000',
                'item'          => '8088 Crystals',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 80 Gems',
                'code_product'  => 'COC80G',
                'price'         => '12000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 500 Gems',
                'code_product'  => 'COC500G',
                'price'         => '60000',
                'item'          => '500 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 2500 Gems',
                'code_product'  => 'COC80G',
                'price'         => '225000',
                'item'          => '2500 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 6500 Gems',
                'code_product'  => 'COC6500G',
                'price'         => '500000',
                'item'          => '6500 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 14000 Gems',
                'code_product'  => 'COC14000G',
                'price'         => '1000000',
                'item'          => '14000 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 80 Gems',
                'code_product'  => 'COC80G',
                'price'         => '17000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 80 Gems',
                'code_product'  => 'COC80G',
                'price'         => '17000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 80 Gems',
                'code_product'  => 'COC80G',
                'price'         => '17000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 80 Gems',
                'code_product'  => 'COC80G',
                'price'         => '17000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 80 Gems',
                'code_product'  => 'COC80G',
                'price'         => '17000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 80 Gems',
                'code_product'  => 'COC80G',
                'price'         => '17000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 80 Gems',
                'code_product'  => 'COC80G',
                'price'         => '17000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '6',
                'name_product'  => 'Clash of Clans 80 Gems',
                'code_product'  => 'COC80G',
                'price'         => '17000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '7',
                'name_product'  => 'Clash Royale 80 Gems',
                'code_product'  => 'CR80G',
                'price'         => '13000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '7',
                'name_product'  => 'Clash Royale 500 Gems',
                'code_product'  => 'CR500G',
                'price'         => '60000',
                'item'          => '500 Gems',
            ],
            [
                'id_item'       => '7',
                'name_product'  => 'Clash Royale Gold Pass',
                'code_product'  => 'CRGP00',
                'price'         => '69000',
                'item'          => 'Gold Pass',
            ],
            [
                'id_item'       => '7',
                'name_product'  => 'Clash Royale 1200 Gems',
                'code_product'  => 'CR1200G',
                'price'         => '115000',
                'item'          => '1200 Gems',
            ],
            [
                'id_item'       => '7',
                'name_product'  => 'Clash Royale Diamond Pass',
                'code_product'  => 'CRDPASS0',
                'price'         => '135000',
                'item'          => 'Diamond Pass',
            ],
            [
                'id_item'       => '7',
                'name_product'  => 'Clash Royale 2500 Gems',
                'code_product'  => 'CR2500G',
                'price'         => '235000',
                'item'          => '2500 Gems',
            ],
            [
                'id_item'       => '7',
                'name_product'  => 'Clash Royale 6500 Gems',
                'code_product'  => 'CR6500G',
                'price'         => '585000',
                'item'          => '6500 Gems',
            ],
            [
                'id_item'       => '7',
                'name_product'  => 'Clash Royale 14000 Gems',
                'code_product'  => 'CR14000G',
                'price'         => '1100000',
                'item'          => '14000 Gems',
            ],
            [
                'id_item'       => '8',
                'name_product'  => 'Brawl Stars 30 Gems',
                'code_product'  => 'BRS30G',
                'price'         => '28000',
                'item'          => '30 Gems',
            ],
            [
                'id_item'       => '8',
                'name_product'  => 'Brawl Stars 80 Gems',
                'code_product'  => 'BRS80G',
                'price'         => '65000',
                'item'          => '80 Gems',
            ],
            [
                'id_item'       => '8',
                'name_product'  => 'Brawl Stars 170  Gems',
                'code_product'  => 'BRS170G',
                'price'         => '13000',
                'item'          => '170  Gems',
            ],
            [
                'id_item'       => '8',
                'name_product'  => 'Brawl Stars Brawl Pass',
                'code_product'  => 'BRSPASS00',
                'price'         => '130000',
                'item'          => 'Brawl Pass',
            ],
            [
                'id_item'       => '8',
                'name_product'  => 'Brawl Stars 360 Gems',
                'code_product'  => 'BRS360G',
                'price'         => '255000',
                'item'          => '360 Gems',
            ],
            [
                'id_item'       => '8',
                'name_product'  => 'Brawl Stars 950 Gems',
                'code_product'  => 'BRS950G',
                'price'         => '640000',
                'item'          => '950 Gems',
            ],
            [
                'id_item'       => '8',
                'name_product'  => 'Brawl Stars 2000 Gems',
                'code_product'  => 'BRS2000G',
                'price'         => '65000',
                'item'          => '2000 Gems',
            ],
            [
                'id_item'       => '9',
                'name_product'  => 'Free Fire 20 Diamond',
                'code_product'  => 'FF20D',
                'price'         => '4000',
                'item'          => '20 Diamond',
            ],
            [
                'id_item'       => '9',
                'name_product'  => 'Free Fire 30 Diamond',
                'code_product'  => 'FF30D',
                'price'         => '6000',
                'item'          => '30 Diamond',
            ],
            [
                'id_item'       => '9',
                'name_product'  => 'Free Fire 40 Diamond',
                'code_product'  => 'FF40D',
                'price'         => '6100',
                'item'          => '40 Diamond',
            ],
            [
                'id_item'       => '9',
                'name_product'  => 'Free Fire 70 Diamond',
                'code_product'  => 'FF70D',
                'price'         => '10000',
                'item'          => '70 Diamond',
            ],
            [
                'id_item'       => '9',
                'name_product'  => 'Free Fire 100 Diamond',
                'code_product'  => 'FF100D',
                'price'         => '14000',
                'item'          => '100 Diamond',
            ],
            [
                'id_item'       => '9',
                'name_product'  => 'Free Fire 150 Diamond',
                'code_product'  => 'FF150D',
                'price'         => '21000',
                'item'          => '150 Diamond',
            ],
            [
                'id_item'       => '9',
                'name_product'  => 'Free Fire 200 Diamond',
                'code_product'  => 'FF200D',
                'price'         => '28000',
                'item'          => '200 Diamond',
            ],
            [
                'id_item'       => '9',
                'name_product'  => 'Free Fire 930 Diamond',
                'code_product'  => 'FF930D',
                'price'         => '140000',
                'item'          => '930 Diamond',
            ],
            [
                'id_item'       => '9',
                'name_product'  => 'Free Fire 1000 Diamond',
                'code_product'  => 'FF1000D',
                'price'         => '150000',
                'item'          => '1000 Diamond',
            ],
            [
                'id_item'       => '9',
                'name_product'  => 'Free Fire 2000 Diamond',
                'code_product'  => 'FF2000D',
                'price'         => '260000',
                'item'          => '2000 Diamond',
            ],
        ];

        $this->db->table('products')->insertBatch($data);
    }
}
